# Generated by Django 4.0.3 on 2022-03-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='picture',
            field=models.ImageField(null=True, upload_to='service_pictures'),
        ),
    ]
