# Generated by Django 4.0.3 on 2022-03-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perritos', '0012_remove_perrito_likes_alter_perrito_gender'),
        ('services', '0002_service_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas', models.TextField(default='', null=True)),
                ('ray_x', models.BooleanField(blank=True, default=False)),
                ('ray_x_results', models.TextField(blank=True, null=True)),
                ('ray_x_file', models.FileField(null=True, upload_to='files_rayx')),
                ('blood_test', models.BooleanField(blank=True, default=False)),
                ('blood_test_results', models.TextField(blank=True, null=True)),
                ('blood_test_file', models.FileField(null=True, upload_to='files_bloodtest')),
                ('general_results', models.TextField(blank=True, null=True)),
                ('medicine', models.TextField(blank=True, null=True)),
                ('hired_service', models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='services.hired_service')),
                ('perrito', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='perritos.perrito')),
            ],
        ),
    ]
