# Generated by Django 3.2.4 on 2022-03-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perritos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perrito',
            name='codigo',
            field=models.CharField(auto_created=True, blank=True, max_length=200, unique=True),
        ),
    ]
