# Generated by Django 3.2.4 on 2022-03-20 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perritos', '0002_perrito_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perrito',
            name='codigo',
        ),
    ]
