# Generated by Django 3.2.4 on 2022-03-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perritos', '0003_remove_perrito_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perrito',
            name='image',
        ),
        migrations.AddField(
            model_name='perrito',
            name='picture',
            field=models.ImageField(default='pictures\\perrito.jpg', upload_to='pictures'),
        ),
    ]
