# Generated by Django 3.2.4 on 2022-03-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perritos', '0004_auto_20220319_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrito',
            name='picture',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
    ]
