# Generated by Django 3.2.4 on 2022-03-20 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perritos', '0005_alter_perrito_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perrito',
            old_name='Gender',
            new_name='gender',
        ),
    ]
