# Generated by Django 3.2.4 on 2022-03-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perritos', '0007_auto_20220319_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='perrito',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
