# Generated by Django 3.2.4 on 2022-03-20 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perritos', '0008_perrito_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perrito',
            name='registerDay',
        ),
    ]
