# Generated by Django 3.2.4 on 2022-03-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perritos', '0009_remove_perrito_registerday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrito',
            name='gender',
            field=models.IntegerField(default=1),
        ),
    ]
