# Generated by Django 4.0.3 on 2022-03-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perritos', '0011_alter_perrito_race'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perrito',
            name='likes',
        ),
        migrations.AlterField(
            model_name='perrito',
            name='gender',
            field=models.CharField(default='no definido', max_length=50),
        ),
    ]
